// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqjvtaktxsaqtgtmiagl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxanZ0YWt0eHNhcXRndG1pYWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0NzY4ODYsImV4cCI6MjEwMjA1Mjg4Nn0.dGvbv81OeLj7j9VWSvb65kWzpt7owD3PIMW6z22E3Zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});